language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
sudo: false
install:
  - dotnet restore ./src/Beefeater.sln
script:
  - dotnet build ./src/Beefeater.sln
  - dotnet test ./src/Beefeater.Tests/Beefeater.Tests.csproj
cache:
  directories:
  - ./BuildPackages