language: csharp
solution: ./src/Beefeater.sln
install:
  - nuget restore ./src/Beefeater.sln
  - chmod +x ./src/packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe
script:
  - xbuild /p:Configuration=Release ./src/Beefeater.sln
  - mono ./src/packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./src/Beefeater.Tests/bin/Release/Beefeater.Tests.dll
after_success:
  - bash <(curl -s https://codecov.io/bash)
