version: 0.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: /ub3L1j8fknd2F4q2iW+waqWIe+0yrnk/l/0OTzPIvfu2hjoOYthlEMwLEaT2pO9
  COVERITY_TOKEN:
    secure: vSFoGG7ATay42KjvJXLqMl/hBthqsp6ZLr6ulbMRFxk=
  COVERITY_EMAIL:
    secure: UEqRjr6WeJQzmybaDQ1x8vGceHZcnwS/K67lMvLKaiE=
  CODECOV_TOKEN:
    secure: KwP1bxxS2EEUh3lSWIc2P5BLBKrjbC9xDKvtN5YjIQ1YqxGAYm+mej73D2KxyK9F
cache:
- BuildPackages -> default.ps1
- C:\ProgramData\chocolatey\bin -> build.environment.ps1
- C:\ProgramData\chocolatey\lib -> build.environment.ps1
install:
- ps: .\build.environment.ps1
- ps: psake appveyor-install
build_script:
- ps: psake appveyor-build
test_script:
- ps: psake appveyor-test
artifacts:
- path: TestResults\BeefeaterCoverage.xml
  name: BeefeaterCoverage.xml
- path: Package\Beefeater.*.zip
- path: Package\Beefeater.*.nupkg
deploy:
- provider: GitHub
  release: $(GitVersion_SemVer)
  auth_token:
    secure: hH6A9i7v+sf5mZy9FLQVG7n4UpLWkUhpshIsia7sGi1ONr+iMKroqjkJk0Hsi3nK
  artifact: /.*\.nupkg/
  prerelease: true
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: 4XLKYHbHXYJuc9SCTYZt5VzxE/XDBpjWSttRIK3ZGux5TwIgAnhMBamo16fjVmzS
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true