version: 1.0.0.{build}
environment:
  COVERALLS_REPO_TOKEN: TODO
  COVERITY_TOKEN:
    secure: vSFoGG7ATay42KjvJXLqMl/hBthqsp6ZLr6ulbMRFxk=
  COVERITY_EMAIL:
    secure: UEqRjr6WeJQzmybaDQ1x8vGceHZcnwS/K67lMvLKaiE=
install:
- ps: .\build.environment.ps1
- ps: psake .\build.tasks.ps1 appveyor-install
build_script:
- ps: psake .\build.tasks.ps1 appveyor-build
test_script:
- ps: psake .\build.tasks.ps1 appveyor-test
artifacts:
- path: BeefeaterCoverage.xml
  name: BeefeaterCoverage.xml
- path: Beefeater.*.zip
- path: Beefeater.*.nupkg
